# Generated by Django 5.2.7 on 2025-10-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_industry_job_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='requirement',
            new_name='requirements',
        ),
    ]
