# Generated by Django 5.2.7 on 2025-12-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='Untitled Resume', max_length=200),
        ),
    ]
