# Generated by Django 5.2.7 on 2025-10-16 08:54

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(default=users.models.get_default_expiry),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp',
            field=models.CharField(max_length=128),
        ),
    ]
